.. Global includes, substitutions, and common links.

.. |author_name| replace:: Yesudeep Mangalapilly
.. |author_email| replace:: yesudeep@gmail.com
.. |copyright| replace:: Copyright 2011 Yesudeep Mangalapilly.
.. |project_name| replace:: ``mom``
.. |project_version| replace:: 0.0.1

.. _issue tracker: http://github.com/gorakhargosh/mom/issues
.. _code repository: http://github.com/gorakhargosh/mom

.. _coverage: http://nedbatchelder.com/code/coverage/
.. _git: http://git-scm.org/
.. _github: http://github.com/
.. _pip: http://pypi.python.org/pypi/pip
.. _Python: http://python.org
.. _sphinx: http://sphinx.pocoo.org/
.. _zc.buildout: http://www.buildout.org/
.. _PyCrypto: http://pycrypto.org/
.. _M2Crypto: http://chandlerproject.org/Projects/MeTooCrypto
.. _pyasn1: http://pypi.python.org/pypi/pyasn1
.. _PEM: http://en.wikipedia.org/wiki/Privacy_Enhanced_Mail
.. _Keyczar RSA private key format: http://code.google.com/p/keyczar/wiki/RsaPrivateKey
.. _Keyczar: http://www.keyczar.org/
.. _OpenSSL: http://www.openssl.org/
